# Desc: Example plugin makefile
# CVS: $Id$

all: libexampledriver.so

%.o: %.cc
	$(CXX) -Wall -fpic -g3 `pkg-config --cflags playercore` -c $<

libexampledriver.so: exampledriver.o
	$(CXX) -shared -nostartfiles -o $@ $^

clean:
	rm -f *.o *.so
