/*
 * This file contains the function table used to tell Player how to serialise
 * your interface messages.
 * The format is as follows:
 *
 * {interface code, message type, message subtype,
 *  pack function, deep copy function, clean up function}
 *
 * Note that a deep copy function and a clean up function are only necessary if
 * the structure used for that message contains dynamically allocated arrays. If
 * they are not needed, specify NULL instead.
 *
 * The XDR functions specified in this table must be linked as a part of the
 * interface library. They can be written by hand, but it may be easier to use
 * the playerxdrgen.py script in PLAYER_SRC/libplayerxdr. For example:
 *
 * python ../../../libplayerxdr/playerxdrgen.py -distro eginterf.h eginterf_xdr.c eginterf_xdr.h
 *
 * The files generated by this script will probably need some cleaning up,
 * especially the header file.
 *
 * The other part of the file is the function that will be exported in the
 * dynamically shared library and imported by the Player server. This must
 * return a pointer to the function table. Clients can link the library at
 * compile time and access the table directly in their call to
 * playerc_add_xdr_ftable(). However, if using multiple plugin interfaces in
 * a client, ensure that they don't use the same name for their function table.
 */

#include "eginterf.h"
#include "eginterf_xdr.h"

// Function table for this interface
static playerxdr_function_t eginterf_ftable[] =
{
  {PLAYER_EGINTERF_CODE, PLAYER_MSGTYPE_DATA, EGINTERF_DATA,
   (player_pack_fn_t)player_eginterf_data_pack, (player_copy_fn_t)player_eginterf_data_copy, (player_cleanup_fn_t)player_eginterf_data_cleanup},
  {PLAYER_EGINTERF_CODE, PLAYER_MSGTYPE_REQ, EGINTERF_REQ,
   (player_pack_fn_t)player_eginterf_req_pack, (player_copy_fn_t)player_eginterf_req_copy, (player_cleanup_fn_t)player_eginterf_req_cleanup},
  {PLAYER_EGINTERF_CODE, PLAYER_MSGTYPE_CMD, EGINTERF_CMD,
   (player_pack_fn_t)player_eginterf_cmd_pack, (player_copy_fn_t)player_eginterf_cmd_copy, (player_cleanup_fn_t)player_eginterf_cmd_cleanup},

  /* This NULL element signals the end of the list */
  {0,0,0,NULL,NULL,NULL}
};

playerxdr_function_t* player_plugininterf_gettable (void)
{
	return eginterf_ftable;
}
