#!/bin/sh

# Run the player bootstrap
set -x
./mkacinclude.sh
aclocal -I /sw/share/aclocal
autoheader
automake --gnu --add-missing
autoconf
./configure "$@"

# Run rtk3 boostrap recusively
#cd rtk3 && ./bootstrap
