/* config.h. Generated by CMake for @PROJECT_NAME@. */

/* Player version string */
#cmakedefine PLAYER_VERSION "${PLAYER_VERSION}"

/* Install prefix */
#define PLAYER_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"

/* Logging level to console and system log */
#cmakedefine DEBUG_LEVEL @DEBUG_LEVEL@

/* enable TCP_NODELAY */
#cmakedefine ENABLE_TCP_NODELAY 1

/* Define to 1 if you have the `cfmakeraw' function. */
#cmakedefine HAVE_CFMAKERAW 1

/* Define to 1 if you have the `dirname' function. */
#cmakedefine HAVE_DIRNAME 1

/* Define to 1 if you have the `getaddrinfo' function. */
#cmakedefine HAVE_GETADDRINFO 1

/* Define to 1 if you have the <jpeglib.h> header file. */
#cmakedefine HAVE_JPEGLIB_H 1

/* Define to 1 if you have the GL library (-lGL). */
#cmakedefine HAVE_LIBGL 1

/* Define to 1 if you have the GLU library (-lGLU). */
#cmakedefine HAVE_LIBGLU 1

/* Define to 1 if you have the GLUT library (-lGglut). */
#cmakedefine HAVE_LIBGLUT 1

/* Define to 1 if you have the jpeg library (-ljpeg). */
#cmakedefine HAVE_LIBJPEG 1

/* Define to 1 if you have the ltdl library (-lltdl). */
#cmakedefine HAVE_LIBLTDL 1

/* Define to 1 if you have the z library (-lz). */
#cmakedefine HAVE_LIBZ 1

/* Define to 1 if you have the <linux/joystick.h> header file. */
#cmakedefine HAVE_LINUX_JOYSTICK_H 1

/* Define to 1 if libplayersd is being built. */
#cmakedefine HAVE_PLAYERSD 1

/* Define to 1 if you have the `poll' function. */
#cmakedefine HAVE_POLL 1

/* Define to 1 if you have the `round' function. */
#cmakedefine HAVE_ROUND 1

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#cmakedefine HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#cmakedefine HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#cmakedefine HAVE_STRING_H 1

/* Define to 1 if you have the <sys/filio.h> header file. */
#cmakedefine HAVE_SYS_FILIO_H 1

/* Define to 1 if you have the <sys/soundcard.h> header file. */
#cmakedefine HAVE_SYS_SOUNDCARD_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#cmakedefine HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#cmakedefine HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H 1

/* Define to 1 if you have the <zlib.h> header file. */
#cmakedefine HAVE_ZLIB_H 1

/* Define to 1 if you do NOT have the compressBound function in libz */
#cmakedefine NEED_COMPRESSBOUND 1

/* Define to 1 if the system is big endian. */
#cmakedefine WORDS_BIGENDIAN 1