#!/bin/sh

cat <<EOF > acinclude.m4
dnl  *****  DO NOT EDIT THIS FILE *****
dnl  This file is automatically generated by mkacinclude.sh.
EOF

for i in \
    m4.d/drivertests.m4
do
    cat $i >> acinclude.m4;
done;

