#
# $Id$
#

include ../../Makefile.common

all: 

dep:

clean_dep:

install: 
	$(MKDIR) -p $(INSTALL_EXAMPLES)/tcl
	$(INSTALL) -m 755 ptz.tcl $(INSTALL_EXAMPLES)/tcl
	$(INSTALL) -m 755 sonarobstacleavoid.tcl $(INSTALL_EXAMPLES)/tcl

uninstall: 
	$(RM) -f $(INSTALL_EXAMPLES)/tcl/ptz.tcl
	$(RM) -f $(INSTALL_EXAMPLES)/tcl/sonarobstacleavoid.tcl

clean:

