# Desc: Example plugin makefile
# CVS: $Id$

all: multidriver.so

%.o: %.cc
	$(CXX) -Wall -fpic -g3 `pkg-config --cflags player` -c $<

%.so: %.o
	$(CXX) -shared -nostartfiles -o $@ $<

clean:
	rm -f *.o *.so
