
# Desc: Example plugin makefile
# CVS: $Id$

all: multidriver.so

%.o: %.cc
	$(CXX) -Wall -fpic -g3 -c $<

%.so: %.o
	$(CXX) -shared -nostartfiles -Wl,-exportdynamic -o $@ $<

clean:
	rm -f *.o *.so
