# Desc: Example plugin makefile
# CVS: $Id$

all: libmultidriver.so

%.o: %.cc
	$(CXX) -Wall -fpic -g3 `pkg-config --cflags playercore` -c $<

libmultidriver.so: multidriver.o
	$(CXX) -shared -nostartfiles -o $@ $^

clean:
	rm -f *.o *.so
