#
# $Id$
#

include ../../Makefile.common

all: 

install:
	$(MKDIR) -p $(INSTALL_LIB)
	$(INSTALL) -m 644 playerclient.tcl $(INSTALL_LIB)

uninstall:
	$(RM) -f $(INSTALL_LIB)/playerclient.tcl 

clean: 
