/*
  * $Id$
  *
  * This file automatically generated by gerkey at: 
  *   Wed Sep 04 11:28:11 PDT 2002
  */


#ifndef SERIALIZE_H
#define SERIALIZE_H

#ifdef __cplusplus
extern "C" {
#endif

int player_ser_player_msghdr(void* dest, player_msghdr_t src);

int player_deser_player_msghdr(player_msghdr_t* dest, void* src);

int player_ser_player_device_id(void* dest, player_device_id_t src);

int player_deser_player_device_id(player_device_id_t* dest, void* src);

int player_ser_player_device_devlist(void* dest, player_device_devlist_t src);

int player_deser_player_device_devlist(player_device_devlist_t* dest, void* src);

int player_ser_player_device_req(void* dest, player_device_req_t src);

int player_deser_player_device_req(player_device_req_t* dest, void* src);

int player_ser_player_device_resp(void* dest, player_device_resp_t src);

int player_deser_player_device_resp(player_device_resp_t* dest, void* src);

int player_ser_player_device_datamode_req(void* dest, player_device_datamode_req_t src);

int player_deser_player_device_datamode_req(player_device_datamode_req_t* dest, void* src);

int player_ser_player_device_datafreq_req(void* dest, player_device_datafreq_req_t src);

int player_deser_player_device_datafreq_req(player_device_datafreq_req_t* dest, void* src);

int player_ser_player_device_auth_req(void* dest, player_device_auth_req_t src);

int player_deser_player_device_auth_req(player_device_auth_req_t* dest, void* src);

int player_ser_player_device_data_req(void* dest, player_device_data_req_t src);

int player_deser_player_device_data_req(player_device_data_req_t* dest, void* src);

int player_ser_player_power_data(void* dest, player_power_data_t src);

int player_deser_player_power_data(player_power_data_t* dest, void* src);

int player_ser_player_gripper_cmd(void* dest, player_gripper_cmd_t src);

int player_deser_player_gripper_cmd(player_gripper_cmd_t* dest, void* src);

int player_ser_player_gripper_data(void* dest, player_gripper_data_t src);

int player_deser_player_gripper_data(player_gripper_data_t* dest, void* src);

int player_ser_player_position_cmd(void* dest, player_position_cmd_t src);

int player_deser_player_position_cmd(player_position_cmd_t* dest, void* src);

int player_ser_player_position_data(void* dest, player_position_data_t src);

int player_deser_player_position_data(player_position_data_t* dest, void* src);

int player_ser_player_position_geom(void* dest, player_position_geom_t src);

int player_deser_player_position_geom(player_position_geom_t* dest, void* src);

int player_ser_player_position_power_config(void* dest, player_position_power_config_t src);

int player_deser_player_position_power_config(player_position_power_config_t* dest, void* src);

int player_ser_player_position_velocitymode_config(void* dest, player_position_velocitymode_config_t src);

int player_deser_player_position_velocitymode_config(player_position_velocitymode_config_t* dest, void* src);

int player_ser_player_position_resetodom_config(void* dest, player_position_resetodom_config_t src);

int player_deser_player_position_resetodom_config(player_position_resetodom_config_t* dest, void* src);

int player_ser_player_sonar_data(void* dest, player_sonar_data_t src);

int player_deser_player_sonar_data(player_sonar_data_t* dest, void* src);

int player_ser_player_sonar_geom(void* dest, player_sonar_geom_t src);

int player_deser_player_sonar_geom(player_sonar_geom_t* dest, void* src);

int player_ser_player_sonar_power_config(void* dest, player_sonar_power_config_t src);

int player_deser_player_sonar_power_config(player_sonar_power_config_t* dest, void* src);

int player_ser_player_laser_data(void* dest, player_laser_data_t src);

int player_deser_player_laser_data(player_laser_data_t* dest, void* src);

int player_ser_player_laser_geom(void* dest, player_laser_geom_t src);

int player_deser_player_laser_geom(player_laser_geom_t* dest, void* src);

int player_ser_player_laser_config(void* dest, player_laser_config_t src);

int player_deser_player_laser_config(player_laser_config_t* dest, void* src);

int player_ser_player_blobfinder_header_elt(void* dest, player_blobfinder_header_elt_t src);

int player_deser_player_blobfinder_header_elt(player_blobfinder_header_elt_t* dest, void* src);

int player_ser_player_blobfinder_blob_elt(void* dest, player_blobfinder_blob_elt_t src);

int player_deser_player_blobfinder_blob_elt(player_blobfinder_blob_elt_t* dest, void* src);

int player_ser_player_blobfinder_data(void* dest, player_blobfinder_data_t src);

int player_deser_player_blobfinder_data(player_blobfinder_data_t* dest, void* src);

int player_ser_player_ptz_cmd(void* dest, player_ptz_cmd_t src);

int player_deser_player_ptz_cmd(player_ptz_cmd_t* dest, void* src);

int player_ser_player_ptz_data(void* dest, player_ptz_data_t src);

int player_deser_player_ptz_data(player_ptz_data_t* dest, void* src);

int player_ser_player_fiducial_item(void* dest, player_fiducial_item_t src);

int player_deser_player_fiducial_item(player_fiducial_item_t* dest, void* src);

int player_ser_player_fiducial_data(void* dest, player_fiducial_data_t src);

int player_deser_player_fiducial_data(player_fiducial_data_t* dest, void* src);

int player_ser_player_fiducial_geom(void* dest, player_fiducial_geom_t src);

int player_deser_player_fiducial_geom(player_fiducial_geom_t* dest, void* src);

int player_ser_player_fiducial_laserbarcode_config(void* dest, player_fiducial_laserbarcode_config_t src);

int player_deser_player_fiducial_laserbarcode_config(player_fiducial_laserbarcode_config_t* dest, void* src);

int player_ser_player_comms_msg(void* dest, player_comms_msg_t src);

int player_deser_player_comms_msg(player_comms_msg_t* dest, void* src);

int player_ser_player_speech_cmd(void* dest, player_speech_cmd_t src);

int player_deser_player_speech_cmd(player_speech_cmd_t* dest, void* src);

int player_ser_player_gps_data(void* dest, player_gps_data_t src);

int player_deser_player_gps_data(player_gps_data_t* dest, void* src);

int player_ser_player_bumper_data(void* dest, player_bumper_data_t src);

int player_deser_player_bumper_data(player_bumper_data_t* dest, void* src);

int player_ser_player_truth_data(void* dest, player_truth_data_t src);

int player_deser_player_truth_data(player_truth_data_t* dest, void* src);

int player_ser_player_truth_pose(void* dest, player_truth_pose_t src);

int player_deser_player_truth_pose(player_truth_pose_t* dest, void* src);

int player_ser_idartx(void* dest, idartx_t src);

int player_deser_idartx(idartx_t* dest, void* src);

int player_ser_idarrx(void* dest, idarrx_t src);

int player_deser_idarrx(idarrx_t* dest, void* src);

int player_ser_player_idar_config(void* dest, player_idar_config_t src);

int player_deser_player_idar_config(player_idar_config_t* dest, void* src);

int player_ser_player_idarturret_reply(void* dest, player_idarturret_reply_t src);

int player_deser_player_idarturret_reply(player_idarturret_reply_t* dest, void* src);

int player_ser_player_idarturret_config(void* dest, player_idarturret_config_t src);

int player_deser_player_idarturret_config(player_idarturret_config_t* dest, void* src);

int player_ser_player_descartes_config(void* dest, player_descartes_config_t src);

int player_deser_player_descartes_config(player_descartes_config_t* dest, void* src);

int player_ser_player_descartes_data(void* dest, player_descartes_data_t src);

int player_deser_player_descartes_data(player_descartes_data_t* dest, void* src);

int player_ser_player_mote_data(void* dest, player_mote_data_t src);

int player_deser_player_mote_data(player_mote_data_t* dest, void* src);

int player_ser_player_mote_config(void* dest, player_mote_config_t src);

int player_deser_player_mote_config(player_mote_config_t* dest, void* src);

int player_ser_player_dio_data(void* dest, player_dio_data_t src);

int player_deser_player_dio_data(player_dio_data_t* dest, void* src);

int player_ser_player_aio_data(void* dest, player_aio_data_t src);

int player_deser_player_aio_data(player_aio_data_t* dest, void* src);

int player_ser_player_bps_data(void* dest, player_bps_data_t src);

int player_deser_player_bps_data(player_bps_data_t* dest, void* src);

int player_ser_player_bps_config(void* dest, player_bps_config_t src);

int player_deser_player_bps_config(player_bps_config_t* dest, void* src);

int player_ser_player_bps_beacon(void* dest, player_bps_beacon_t src);

int player_deser_player_bps_beacon(player_bps_beacon_t* dest, void* src);

int player_ser_player_joystick_data(void* dest, player_joystick_data_t src);

int player_deser_player_joystick_data(player_joystick_data_t* dest, void* src);

int player_ser_player_rwi_config(void* dest, player_rwi_config_t src);

int player_deser_player_rwi_config(player_rwi_config_t* dest, void* src);

#ifdef __cplusplus
}
#endif

#endif
