/*
  * $Id$
  *
  * This file automatically generated by gerkey at: 
  *   Wed Sep 04 11:17:30 PDT 2002
  */


#include <player.h>
#include <serialize.h>

#include <netinet/in.h>
#include <string.h>


int
player_ser_player_msghdr(void* dest, player_msghdr_t src)
{
  int i = 0;


  player_msghdr_t swappedsrc;

  swappedsrc.stx = htons(src.stx);
  memcpy(((char*)dest)+i, &(swappedsrc.stx), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.type = htons(src.type);
  memcpy(((char*)dest)+i, &(swappedsrc.type), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.device = htons(src.device);
  memcpy(((char*)dest)+i, &(swappedsrc.device), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.device_index = htons(src.device_index);
  memcpy(((char*)dest)+i, &(swappedsrc.device_index), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.time_sec = htonl(src.time_sec);
  memcpy(((char*)dest)+i, &(swappedsrc.time_sec), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.time_usec = htonl(src.time_usec);
  memcpy(((char*)dest)+i, &(swappedsrc.time_usec), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.timestamp_sec = htonl(src.timestamp_sec);
  memcpy(((char*)dest)+i, &(swappedsrc.timestamp_sec), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.timestamp_usec = htonl(src.timestamp_usec);
  memcpy(((char*)dest)+i, &(swappedsrc.timestamp_usec), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.reserved = htonl(src.reserved);
  memcpy(((char*)dest)+i, &(swappedsrc.reserved), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.size = htonl(src.size);
  memcpy(((char*)dest)+i, &(swappedsrc.size), sizeof(uint32_t));
  i += sizeof(uint32_t);

  return(i);
}
int
player_deser_player_msghdr(player_msghdr_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->stx), ((char*)src)+i, sizeof(uint16_t));
  dest->stx = ntohs(dest->stx);
  i += sizeof(uint16_t);
  memcpy(&(dest->type), ((char*)src)+i, sizeof(uint16_t));
  dest->type = ntohs(dest->type);
  i += sizeof(uint16_t);
  memcpy(&(dest->device), ((char*)src)+i, sizeof(uint16_t));
  dest->device = ntohs(dest->device);
  i += sizeof(uint16_t);
  memcpy(&(dest->device_index), ((char*)src)+i, sizeof(uint16_t));
  dest->device_index = ntohs(dest->device_index);
  i += sizeof(uint16_t);
  memcpy(&(dest->time_sec), ((char*)src)+i, sizeof(uint32_t));
  dest->time_sec = ntohl(dest->time_sec);
  i += sizeof(uint32_t);
  memcpy(&(dest->time_usec), ((char*)src)+i, sizeof(uint32_t));
  dest->time_usec = ntohl(dest->time_usec);
  i += sizeof(uint32_t);
  memcpy(&(dest->timestamp_sec), ((char*)src)+i, sizeof(uint32_t));
  dest->timestamp_sec = ntohl(dest->timestamp_sec);
  i += sizeof(uint32_t);
  memcpy(&(dest->timestamp_usec), ((char*)src)+i, sizeof(uint32_t));
  dest->timestamp_usec = ntohl(dest->timestamp_usec);
  i += sizeof(uint32_t);
  memcpy(&(dest->reserved), ((char*)src)+i, sizeof(uint32_t));
  dest->reserved = ntohl(dest->reserved);
  i += sizeof(uint32_t);
  memcpy(&(dest->size), ((char*)src)+i, sizeof(uint32_t));
  dest->size = ntohl(dest->size);
  i += sizeof(uint32_t);

  return(i);
}

int
player_ser_player_device_id(void* dest, player_device_id_t src)
{
  int i = 0;


  player_device_id_t swappedsrc;

  swappedsrc.code = htons(src.code);
  memcpy(((char*)dest)+i, &(swappedsrc.code), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.index = htons(src.index);
  memcpy(((char*)dest)+i, &(swappedsrc.index), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.port = htons(src.port);
  memcpy(((char*)dest)+i, &(swappedsrc.port), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_device_id(player_device_id_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->code), ((char*)src)+i, sizeof(uint16_t));
  dest->code = ntohs(dest->code);
  i += sizeof(uint16_t);
  memcpy(&(dest->index), ((char*)src)+i, sizeof(uint16_t));
  dest->index = ntohs(dest->index);
  i += sizeof(uint16_t);
  memcpy(&(dest->port), ((char*)src)+i, sizeof(uint16_t));
  dest->port = ntohs(dest->port);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_device_devlist(void* dest, player_device_devlist_t src)
{
  int i = 0;


  player_device_devlist_t swappedsrc;

  swappedsrc.subtype = htons(src.subtype);
  memcpy(((char*)dest)+i, &(swappedsrc.subtype), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.device_count = htons(src.device_count);
  memcpy(((char*)dest)+i, &(swappedsrc.device_count), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_device_devlist(player_device_devlist_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint16_t));
  dest->subtype = ntohs(dest->subtype);
  i += sizeof(uint16_t);
  memcpy(&(dest->device_count), ((char*)src)+i, sizeof(uint16_t));
  dest->device_count = ntohs(dest->device_count);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_device_req(void* dest, player_device_req_t src)
{
  int i = 0;


  player_device_req_t swappedsrc;

  swappedsrc.subtype = htons(src.subtype);
  memcpy(((char*)dest)+i, &(swappedsrc.subtype), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.code = htons(src.code);
  memcpy(((char*)dest)+i, &(swappedsrc.code), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.index = htons(src.index);
  memcpy(((char*)dest)+i, &(swappedsrc.index), sizeof(uint16_t));
  i += sizeof(uint16_t);
  memcpy(((char*)dest)+i, &(src.access), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_device_req(player_device_req_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint16_t));
  dest->subtype = ntohs(dest->subtype);
  i += sizeof(uint16_t);
  memcpy(&(dest->code), ((char*)src)+i, sizeof(uint16_t));
  dest->code = ntohs(dest->code);
  i += sizeof(uint16_t);
  memcpy(&(dest->index), ((char*)src)+i, sizeof(uint16_t));
  dest->index = ntohs(dest->index);
  i += sizeof(uint16_t);
  memcpy(&(dest->access), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_device_resp(void* dest, player_device_resp_t src)
{
  int i = 0;


  player_device_resp_t swappedsrc;

  swappedsrc.subtype = htons(src.subtype);
  memcpy(((char*)dest)+i, &(swappedsrc.subtype), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.code = htons(src.code);
  memcpy(((char*)dest)+i, &(swappedsrc.code), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.index = htons(src.index);
  memcpy(((char*)dest)+i, &(swappedsrc.index), sizeof(uint16_t));
  i += sizeof(uint16_t);
  memcpy(((char*)dest)+i, &(src.access), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_device_resp(player_device_resp_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint16_t));
  dest->subtype = ntohs(dest->subtype);
  i += sizeof(uint16_t);
  memcpy(&(dest->code), ((char*)src)+i, sizeof(uint16_t));
  dest->code = ntohs(dest->code);
  i += sizeof(uint16_t);
  memcpy(&(dest->index), ((char*)src)+i, sizeof(uint16_t));
  dest->index = ntohs(dest->index);
  i += sizeof(uint16_t);
  memcpy(&(dest->access), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_device_datamode_req(void* dest, player_device_datamode_req_t src)
{
  int i = 0;


  player_device_datamode_req_t swappedsrc;

  swappedsrc.subtype = htons(src.subtype);
  memcpy(((char*)dest)+i, &(swappedsrc.subtype), sizeof(uint16_t));
  i += sizeof(uint16_t);
  memcpy(((char*)dest)+i, &(src.mode), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_device_datamode_req(player_device_datamode_req_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint16_t));
  dest->subtype = ntohs(dest->subtype);
  i += sizeof(uint16_t);
  memcpy(&(dest->mode), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_device_datafreq_req(void* dest, player_device_datafreq_req_t src)
{
  int i = 0;


  player_device_datafreq_req_t swappedsrc;

  swappedsrc.subtype = htons(src.subtype);
  memcpy(((char*)dest)+i, &(swappedsrc.subtype), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.frequency = htons(src.frequency);
  memcpy(((char*)dest)+i, &(swappedsrc.frequency), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_device_datafreq_req(player_device_datafreq_req_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint16_t));
  dest->subtype = ntohs(dest->subtype);
  i += sizeof(uint16_t);
  memcpy(&(dest->frequency), ((char*)src)+i, sizeof(uint16_t));
  dest->frequency = ntohs(dest->frequency);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_device_auth_req(void* dest, player_device_auth_req_t src)
{
  int i = 0;


  player_device_auth_req_t swappedsrc;

  swappedsrc.subtype = htons(src.subtype);
  memcpy(((char*)dest)+i, &(swappedsrc.subtype), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_device_auth_req(player_device_auth_req_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint16_t));
  dest->subtype = ntohs(dest->subtype);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_device_data_req(void* dest, player_device_data_req_t src)
{
  int i = 0;


  player_device_data_req_t swappedsrc;

  swappedsrc.subtype = htons(src.subtype);
  memcpy(((char*)dest)+i, &(swappedsrc.subtype), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_device_data_req(player_device_data_req_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint16_t));
  dest->subtype = ntohs(dest->subtype);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_power_data(void* dest, player_power_data_t src)
{
  int i = 0;


  player_power_data_t swappedsrc;

  swappedsrc.charge = htons(src.charge);
  memcpy(((char*)dest)+i, &(swappedsrc.charge), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_power_data(player_power_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->charge), ((char*)src)+i, sizeof(uint16_t));
  dest->charge = ntohs(dest->charge);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_gripper_cmd(void* dest, player_gripper_cmd_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.cmd), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.arg), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_gripper_cmd(player_gripper_cmd_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->cmd), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->arg), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_gripper_data(void* dest, player_gripper_data_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.state), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.beams), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_gripper_data(player_gripper_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->state), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->beams), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_position_cmd(void* dest, player_position_cmd_t src)
{
  int i = 0;


  player_position_cmd_t swappedsrc;

  swappedsrc.xpos = htonl(src.xpos);
  memcpy(((char*)dest)+i, &(swappedsrc.xpos), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.ypos = htonl(src.ypos);
  memcpy(((char*)dest)+i, &(swappedsrc.ypos), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.yaw = htonl(src.yaw);
  memcpy(((char*)dest)+i, &(swappedsrc.yaw), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.xspeed = htonl(src.xspeed);
  memcpy(((char*)dest)+i, &(swappedsrc.xspeed), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.yspeed = htonl(src.yspeed);
  memcpy(((char*)dest)+i, &(swappedsrc.yspeed), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.yawspeed = htonl(src.yawspeed);
  memcpy(((char*)dest)+i, &(swappedsrc.yawspeed), sizeof(uint32_t));
  i += sizeof(uint32_t);

  return(i);
}
int
player_deser_player_position_cmd(player_position_cmd_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->xpos), ((char*)src)+i, sizeof(uint32_t));
  dest->xpos = ntohl(dest->xpos);
  i += sizeof(uint32_t);
  memcpy(&(dest->ypos), ((char*)src)+i, sizeof(uint32_t));
  dest->ypos = ntohl(dest->ypos);
  i += sizeof(uint32_t);
  memcpy(&(dest->yaw), ((char*)src)+i, sizeof(uint32_t));
  dest->yaw = ntohl(dest->yaw);
  i += sizeof(uint32_t);
  memcpy(&(dest->xspeed), ((char*)src)+i, sizeof(uint32_t));
  dest->xspeed = ntohl(dest->xspeed);
  i += sizeof(uint32_t);
  memcpy(&(dest->yspeed), ((char*)src)+i, sizeof(uint32_t));
  dest->yspeed = ntohl(dest->yspeed);
  i += sizeof(uint32_t);
  memcpy(&(dest->yawspeed), ((char*)src)+i, sizeof(uint32_t));
  dest->yawspeed = ntohl(dest->yawspeed);
  i += sizeof(uint32_t);

  return(i);
}

int
player_ser_player_position_data(void* dest, player_position_data_t src)
{
  int i = 0;


  player_position_data_t swappedsrc;

  swappedsrc.xpos = htonl(src.xpos);
  memcpy(((char*)dest)+i, &(swappedsrc.xpos), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.ypos = htonl(src.ypos);
  memcpy(((char*)dest)+i, &(swappedsrc.ypos), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.yaw = htonl(src.yaw);
  memcpy(((char*)dest)+i, &(swappedsrc.yaw), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.xspeed = htonl(src.xspeed);
  memcpy(((char*)dest)+i, &(swappedsrc.xspeed), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.yspeed = htonl(src.yspeed);
  memcpy(((char*)dest)+i, &(swappedsrc.yspeed), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.yawspeed = htonl(src.yawspeed);
  memcpy(((char*)dest)+i, &(swappedsrc.yawspeed), sizeof(uint32_t));
  i += sizeof(uint32_t);
  memcpy(((char*)dest)+i, &(src.stall), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_position_data(player_position_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->xpos), ((char*)src)+i, sizeof(uint32_t));
  dest->xpos = ntohl(dest->xpos);
  i += sizeof(uint32_t);
  memcpy(&(dest->ypos), ((char*)src)+i, sizeof(uint32_t));
  dest->ypos = ntohl(dest->ypos);
  i += sizeof(uint32_t);
  memcpy(&(dest->yaw), ((char*)src)+i, sizeof(uint32_t));
  dest->yaw = ntohl(dest->yaw);
  i += sizeof(uint32_t);
  memcpy(&(dest->xspeed), ((char*)src)+i, sizeof(uint32_t));
  dest->xspeed = ntohl(dest->xspeed);
  i += sizeof(uint32_t);
  memcpy(&(dest->yspeed), ((char*)src)+i, sizeof(uint32_t));
  dest->yspeed = ntohl(dest->yspeed);
  i += sizeof(uint32_t);
  memcpy(&(dest->yawspeed), ((char*)src)+i, sizeof(uint32_t));
  dest->yawspeed = ntohl(dest->yawspeed);
  i += sizeof(uint32_t);
  memcpy(&(dest->stall), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_position_geom(void* dest, player_position_geom_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_position_geom(player_position_geom_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_position_power_config(void* dest, player_position_power_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.request), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.value), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_position_power_config(player_position_power_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->request), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->value), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_position_velocitymode_config(void* dest, player_position_velocitymode_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.request), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.value), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_position_velocitymode_config(player_position_velocitymode_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->request), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->value), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_position_resetodom_config(void* dest, player_position_resetodom_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.request), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_position_resetodom_config(player_position_resetodom_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->request), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_sonar_data(void* dest, player_sonar_data_t src)
{
  int i = 0;


  player_sonar_data_t swappedsrc;

  swappedsrc.range_count = htons(src.range_count);
  memcpy(((char*)dest)+i, &(swappedsrc.range_count), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_sonar_data(player_sonar_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->range_count), ((char*)src)+i, sizeof(uint16_t));
  dest->range_count = ntohs(dest->range_count);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_sonar_geom(void* dest, player_sonar_geom_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);

  player_sonar_geom_t swappedsrc;

  swappedsrc.pose_count = htons(src.pose_count);
  memcpy(((char*)dest)+i, &(swappedsrc.pose_count), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_sonar_geom(player_sonar_geom_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->pose_count), ((char*)src)+i, sizeof(uint16_t));
  dest->pose_count = ntohs(dest->pose_count);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_sonar_power_config(void* dest, player_sonar_power_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.value), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_sonar_power_config(player_sonar_power_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->value), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_laser_data(void* dest, player_laser_data_t src)
{
  int i = 0;


  player_laser_data_t swappedsrc;

  swappedsrc.min_angle = htons(src.min_angle);
  memcpy(((char*)dest)+i, &(swappedsrc.min_angle), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.max_angle = htons(src.max_angle);
  memcpy(((char*)dest)+i, &(swappedsrc.max_angle), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.resolution = htons(src.resolution);
  memcpy(((char*)dest)+i, &(swappedsrc.resolution), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.range_count = htons(src.range_count);
  memcpy(((char*)dest)+i, &(swappedsrc.range_count), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_laser_data(player_laser_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->min_angle), ((char*)src)+i, sizeof(uint16_t));
  dest->min_angle = ntohs(dest->min_angle);
  i += sizeof(uint16_t);
  memcpy(&(dest->max_angle), ((char*)src)+i, sizeof(uint16_t));
  dest->max_angle = ntohs(dest->max_angle);
  i += sizeof(uint16_t);
  memcpy(&(dest->resolution), ((char*)src)+i, sizeof(uint16_t));
  dest->resolution = ntohs(dest->resolution);
  i += sizeof(uint16_t);
  memcpy(&(dest->range_count), ((char*)src)+i, sizeof(uint16_t));
  dest->range_count = ntohs(dest->range_count);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_laser_geom(void* dest, player_laser_geom_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_laser_geom(player_laser_geom_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_laser_config(void* dest, player_laser_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);

  player_laser_config_t swappedsrc;

  swappedsrc.min_angle = htons(src.min_angle);
  memcpy(((char*)dest)+i, &(swappedsrc.min_angle), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.max_angle = htons(src.max_angle);
  memcpy(((char*)dest)+i, &(swappedsrc.max_angle), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.resolution = htons(src.resolution);
  memcpy(((char*)dest)+i, &(swappedsrc.resolution), sizeof(uint16_t));
  i += sizeof(uint16_t);
  memcpy(((char*)dest)+i, &(src.intensity), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_laser_config(player_laser_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->min_angle), ((char*)src)+i, sizeof(uint16_t));
  dest->min_angle = ntohs(dest->min_angle);
  i += sizeof(uint16_t);
  memcpy(&(dest->max_angle), ((char*)src)+i, sizeof(uint16_t));
  dest->max_angle = ntohs(dest->max_angle);
  i += sizeof(uint16_t);
  memcpy(&(dest->resolution), ((char*)src)+i, sizeof(uint16_t));
  dest->resolution = ntohs(dest->resolution);
  i += sizeof(uint16_t);
  memcpy(&(dest->intensity), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_blobfinder_header_elt(void* dest, player_blobfinder_header_elt_t src)
{
  int i = 0;


  player_blobfinder_header_elt_t swappedsrc;

  swappedsrc.index = htons(src.index);
  memcpy(((char*)dest)+i, &(swappedsrc.index), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.num = htons(src.num);
  memcpy(((char*)dest)+i, &(swappedsrc.num), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_blobfinder_header_elt(player_blobfinder_header_elt_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->index), ((char*)src)+i, sizeof(uint16_t));
  dest->index = ntohs(dest->index);
  i += sizeof(uint16_t);
  memcpy(&(dest->num), ((char*)src)+i, sizeof(uint16_t));
  dest->num = ntohs(dest->num);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_blobfinder_blob_elt(void* dest, player_blobfinder_blob_elt_t src)
{
  int i = 0;


  player_blobfinder_blob_elt_t swappedsrc;

  swappedsrc.color = htonl(src.color);
  memcpy(((char*)dest)+i, &(swappedsrc.color), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.area = htonl(src.area);
  memcpy(((char*)dest)+i, &(swappedsrc.area), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.x = htons(src.x);
  memcpy(((char*)dest)+i, &(swappedsrc.x), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.y = htons(src.y);
  memcpy(((char*)dest)+i, &(swappedsrc.y), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.left = htons(src.left);
  memcpy(((char*)dest)+i, &(swappedsrc.left), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.right = htons(src.right);
  memcpy(((char*)dest)+i, &(swappedsrc.right), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.top = htons(src.top);
  memcpy(((char*)dest)+i, &(swappedsrc.top), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.bottom = htons(src.bottom);
  memcpy(((char*)dest)+i, &(swappedsrc.bottom), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.range = htons(src.range);
  memcpy(((char*)dest)+i, &(swappedsrc.range), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_blobfinder_blob_elt(player_blobfinder_blob_elt_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->color), ((char*)src)+i, sizeof(uint32_t));
  dest->color = ntohl(dest->color);
  i += sizeof(uint32_t);
  memcpy(&(dest->area), ((char*)src)+i, sizeof(uint32_t));
  dest->area = ntohl(dest->area);
  i += sizeof(uint32_t);
  memcpy(&(dest->x), ((char*)src)+i, sizeof(uint16_t));
  dest->x = ntohs(dest->x);
  i += sizeof(uint16_t);
  memcpy(&(dest->y), ((char*)src)+i, sizeof(uint16_t));
  dest->y = ntohs(dest->y);
  i += sizeof(uint16_t);
  memcpy(&(dest->left), ((char*)src)+i, sizeof(uint16_t));
  dest->left = ntohs(dest->left);
  i += sizeof(uint16_t);
  memcpy(&(dest->right), ((char*)src)+i, sizeof(uint16_t));
  dest->right = ntohs(dest->right);
  i += sizeof(uint16_t);
  memcpy(&(dest->top), ((char*)src)+i, sizeof(uint16_t));
  dest->top = ntohs(dest->top);
  i += sizeof(uint16_t);
  memcpy(&(dest->bottom), ((char*)src)+i, sizeof(uint16_t));
  dest->bottom = ntohs(dest->bottom);
  i += sizeof(uint16_t);
  memcpy(&(dest->range), ((char*)src)+i, sizeof(uint16_t));
  dest->range = ntohs(dest->range);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_blobfinder_data(void* dest, player_blobfinder_data_t src)
{
  int i = 0;


  player_blobfinder_data_t swappedsrc;

  swappedsrc.width = htons(src.width);
  memcpy(((char*)dest)+i, &(swappedsrc.width), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.height = htons(src.height);
  memcpy(((char*)dest)+i, &(swappedsrc.height), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_blobfinder_data(player_blobfinder_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->width), ((char*)src)+i, sizeof(uint16_t));
  dest->width = ntohs(dest->width);
  i += sizeof(uint16_t);
  memcpy(&(dest->height), ((char*)src)+i, sizeof(uint16_t));
  dest->height = ntohs(dest->height);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_ptz_cmd(void* dest, player_ptz_cmd_t src)
{
  int i = 0;


  player_ptz_cmd_t swappedsrc;

  swappedsrc.pan = htons(src.pan);
  memcpy(((char*)dest)+i, &(swappedsrc.pan), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.tilt = htons(src.tilt);
  memcpy(((char*)dest)+i, &(swappedsrc.tilt), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.zoom = htons(src.zoom);
  memcpy(((char*)dest)+i, &(swappedsrc.zoom), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_ptz_cmd(player_ptz_cmd_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->pan), ((char*)src)+i, sizeof(uint16_t));
  dest->pan = ntohs(dest->pan);
  i += sizeof(uint16_t);
  memcpy(&(dest->tilt), ((char*)src)+i, sizeof(uint16_t));
  dest->tilt = ntohs(dest->tilt);
  i += sizeof(uint16_t);
  memcpy(&(dest->zoom), ((char*)src)+i, sizeof(uint16_t));
  dest->zoom = ntohs(dest->zoom);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_ptz_data(void* dest, player_ptz_data_t src)
{
  int i = 0;


  player_ptz_data_t swappedsrc;

  swappedsrc.pan = htons(src.pan);
  memcpy(((char*)dest)+i, &(swappedsrc.pan), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.tilt = htons(src.tilt);
  memcpy(((char*)dest)+i, &(swappedsrc.tilt), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.zoom = htons(src.zoom);
  memcpy(((char*)dest)+i, &(swappedsrc.zoom), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_ptz_data(player_ptz_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->pan), ((char*)src)+i, sizeof(uint16_t));
  dest->pan = ntohs(dest->pan);
  i += sizeof(uint16_t);
  memcpy(&(dest->tilt), ((char*)src)+i, sizeof(uint16_t));
  dest->tilt = ntohs(dest->tilt);
  i += sizeof(uint16_t);
  memcpy(&(dest->zoom), ((char*)src)+i, sizeof(uint16_t));
  dest->zoom = ntohs(dest->zoom);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_fiducial_item(void* dest, player_fiducial_item_t src)
{
  int i = 0;


  player_fiducial_item_t swappedsrc;

  swappedsrc.id = htons(src.id);
  memcpy(((char*)dest)+i, &(swappedsrc.id), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_fiducial_item(player_fiducial_item_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->id), ((char*)src)+i, sizeof(uint16_t));
  dest->id = ntohs(dest->id);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_fiducial_data(void* dest, player_fiducial_data_t src)
{
  int i = 0;


  player_fiducial_data_t swappedsrc;

  swappedsrc.count = htons(src.count);
  memcpy(((char*)dest)+i, &(swappedsrc.count), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_fiducial_data(player_fiducial_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->count), ((char*)src)+i, sizeof(uint16_t));
  dest->count = ntohs(dest->count);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_fiducial_geom(void* dest, player_fiducial_geom_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_fiducial_geom(player_fiducial_geom_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_fiducial_laserbarcode_config(void* dest, player_fiducial_laserbarcode_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.bit_count), sizeof(uint8_t));
  i += sizeof(uint8_t);

  player_fiducial_laserbarcode_config_t swappedsrc;

  swappedsrc.bit_size = htons(src.bit_size);
  memcpy(((char*)dest)+i, &(swappedsrc.bit_size), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.zero_thresh = htons(src.zero_thresh);
  memcpy(((char*)dest)+i, &(swappedsrc.zero_thresh), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.one_thresh = htons(src.one_thresh);
  memcpy(((char*)dest)+i, &(swappedsrc.one_thresh), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_fiducial_laserbarcode_config(player_fiducial_laserbarcode_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->bit_count), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->bit_size), ((char*)src)+i, sizeof(uint16_t));
  dest->bit_size = ntohs(dest->bit_size);
  i += sizeof(uint16_t);
  memcpy(&(dest->zero_thresh), ((char*)src)+i, sizeof(uint16_t));
  dest->zero_thresh = ntohs(dest->zero_thresh);
  i += sizeof(uint16_t);
  memcpy(&(dest->one_thresh), ((char*)src)+i, sizeof(uint16_t));
  dest->one_thresh = ntohs(dest->one_thresh);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_comms_msg(void* dest, player_comms_msg_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_comms_msg(player_comms_msg_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_speech_cmd(void* dest, player_speech_cmd_t src)
{
  int i = 0;


  return(i);
}
int
player_deser_player_speech_cmd(player_speech_cmd_t* dest, void* src)
{
  int i = 0;


  return(i);
}

int
player_ser_player_gps_data(void* dest, player_gps_data_t src)
{
  int i = 0;


  player_gps_data_t swappedsrc;

  swappedsrc.xpos = htonl(src.xpos);
  memcpy(((char*)dest)+i, &(swappedsrc.xpos), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.ypos = htonl(src.ypos);
  memcpy(((char*)dest)+i, &(swappedsrc.ypos), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.heading = htonl(src.heading);
  memcpy(((char*)dest)+i, &(swappedsrc.heading), sizeof(uint32_t));
  i += sizeof(uint32_t);

  return(i);
}
int
player_deser_player_gps_data(player_gps_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->xpos), ((char*)src)+i, sizeof(uint32_t));
  dest->xpos = ntohl(dest->xpos);
  i += sizeof(uint32_t);
  memcpy(&(dest->ypos), ((char*)src)+i, sizeof(uint32_t));
  dest->ypos = ntohl(dest->ypos);
  i += sizeof(uint32_t);
  memcpy(&(dest->heading), ((char*)src)+i, sizeof(uint32_t));
  dest->heading = ntohl(dest->heading);
  i += sizeof(uint32_t);

  return(i);
}

int
player_ser_player_bumper_data(void* dest, player_bumper_data_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.bumper_count), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_bumper_data(player_bumper_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->bumper_count), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_truth_data(void* dest, player_truth_data_t src)
{
  int i = 0;


  player_truth_data_t swappedsrc;

  swappedsrc.px = htonl(src.px);
  memcpy(((char*)dest)+i, &(swappedsrc.px), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.py = htonl(src.py);
  memcpy(((char*)dest)+i, &(swappedsrc.py), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.pa = htonl(src.pa);
  memcpy(((char*)dest)+i, &(swappedsrc.pa), sizeof(uint32_t));
  i += sizeof(uint32_t);

  return(i);
}
int
player_deser_player_truth_data(player_truth_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->px), ((char*)src)+i, sizeof(uint32_t));
  dest->px = ntohl(dest->px);
  i += sizeof(uint32_t);
  memcpy(&(dest->py), ((char*)src)+i, sizeof(uint32_t));
  dest->py = ntohl(dest->py);
  i += sizeof(uint32_t);
  memcpy(&(dest->pa), ((char*)src)+i, sizeof(uint32_t));
  dest->pa = ntohl(dest->pa);
  i += sizeof(uint32_t);

  return(i);
}

int
player_ser_player_truth_pose(void* dest, player_truth_pose_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);

  player_truth_pose_t swappedsrc;

  swappedsrc.px = htonl(src.px);
  memcpy(((char*)dest)+i, &(swappedsrc.px), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.py = htonl(src.py);
  memcpy(((char*)dest)+i, &(swappedsrc.py), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.pa = htonl(src.pa);
  memcpy(((char*)dest)+i, &(swappedsrc.pa), sizeof(uint32_t));
  i += sizeof(uint32_t);

  return(i);
}
int
player_deser_player_truth_pose(player_truth_pose_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->px), ((char*)src)+i, sizeof(uint32_t));
  dest->px = ntohl(dest->px);
  i += sizeof(uint32_t);
  memcpy(&(dest->py), ((char*)src)+i, sizeof(uint32_t));
  dest->py = ntohl(dest->py);
  i += sizeof(uint32_t);
  memcpy(&(dest->pa), ((char*)src)+i, sizeof(uint32_t));
  dest->pa = ntohl(dest->pa);
  i += sizeof(uint32_t);

  return(i);
}

int
player_ser_idartx(void* dest, idartx_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.len), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.intensity), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_idartx(idartx_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->len), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->intensity), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_idarrx(void* dest, idarrx_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.len), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.intensity), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.reflection), sizeof(uint8_t));
  i += sizeof(uint8_t);

  idarrx_t swappedsrc;

  swappedsrc.timestamp_sec = htonl(src.timestamp_sec);
  memcpy(((char*)dest)+i, &(swappedsrc.timestamp_sec), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.timestamp_usec = htonl(src.timestamp_usec);
  memcpy(((char*)dest)+i, &(swappedsrc.timestamp_usec), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.range = htons(src.range);
  memcpy(((char*)dest)+i, &(swappedsrc.range), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_idarrx(idarrx_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->len), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->intensity), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->reflection), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->timestamp_sec), ((char*)src)+i, sizeof(uint32_t));
  dest->timestamp_sec = ntohl(dest->timestamp_sec);
  i += sizeof(uint32_t);
  memcpy(&(dest->timestamp_usec), ((char*)src)+i, sizeof(uint32_t));
  dest->timestamp_usec = ntohl(dest->timestamp_usec);
  i += sizeof(uint32_t);
  memcpy(&(dest->range), ((char*)src)+i, sizeof(uint16_t));
  dest->range = ntohs(dest->range);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_idar_config(void* dest, player_idar_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.instruction), sizeof(uint8_t));
  i += sizeof(uint8_t);
  i += player_ser_idartx(((char*)dest)+i, src.tx);

  return(i);
}
int
player_deser_player_idar_config(player_idar_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->instruction), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  i += player_deser_idartx(&(dest->tx), ((char*)src)+i);

  return(i);
}

int
player_ser_player_idarturret_reply(void* dest, player_idarturret_reply_t src)
{
  int i = 0;


  return(i);
}
int
player_deser_player_idarturret_reply(player_idarturret_reply_t* dest, void* src)
{
  int i = 0;


  return(i);
}

int
player_ser_player_idarturret_config(void* dest, player_idarturret_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.instruction), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_idarturret_config(player_idarturret_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->instruction), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_descartes_config(void* dest, player_descartes_config_t src)
{
  int i = 0;


  player_descartes_config_t swappedsrc;

  swappedsrc.speed = htons(src.speed);
  memcpy(((char*)dest)+i, &(swappedsrc.speed), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.heading = htons(src.heading);
  memcpy(((char*)dest)+i, &(swappedsrc.heading), sizeof(uint16_t));
  i += sizeof(uint16_t);
  swappedsrc.distance = htons(src.distance);
  memcpy(((char*)dest)+i, &(swappedsrc.distance), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_descartes_config(player_descartes_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->speed), ((char*)src)+i, sizeof(uint16_t));
  dest->speed = ntohs(dest->speed);
  i += sizeof(uint16_t);
  memcpy(&(dest->heading), ((char*)src)+i, sizeof(uint16_t));
  dest->heading = ntohs(dest->heading);
  i += sizeof(uint16_t);
  memcpy(&(dest->distance), ((char*)src)+i, sizeof(uint16_t));
  dest->distance = ntohs(dest->distance);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_descartes_data(void* dest, player_descartes_data_t src)
{
  int i = 0;


  player_descartes_data_t swappedsrc;

  swappedsrc.xpos = htonl(src.xpos);
  memcpy(((char*)dest)+i, &(swappedsrc.xpos), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.ypos = htonl(src.ypos);
  memcpy(((char*)dest)+i, &(swappedsrc.ypos), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.theta = htons(src.theta);
  memcpy(((char*)dest)+i, &(swappedsrc.theta), sizeof(uint16_t));
  i += sizeof(uint16_t);

  return(i);
}
int
player_deser_player_descartes_data(player_descartes_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->xpos), ((char*)src)+i, sizeof(uint32_t));
  dest->xpos = ntohl(dest->xpos);
  i += sizeof(uint32_t);
  memcpy(&(dest->ypos), ((char*)src)+i, sizeof(uint32_t));
  dest->ypos = ntohl(dest->ypos);
  i += sizeof(uint32_t);
  memcpy(&(dest->theta), ((char*)src)+i, sizeof(uint16_t));
  dest->theta = ntohs(dest->theta);
  i += sizeof(uint16_t);

  return(i);
}

int
player_ser_player_mote_data(void* dest, player_mote_data_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.len), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_mote_data(player_mote_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->len), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_mote_config(void* dest, player_mote_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.strength), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_mote_config(player_mote_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->strength), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_dio_data(void* dest, player_dio_data_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.count), sizeof(uint8_t));
  i += sizeof(uint8_t);

  player_dio_data_t swappedsrc;

  swappedsrc.digin = htonl(src.digin);
  memcpy(((char*)dest)+i, &(swappedsrc.digin), sizeof(uint32_t));
  i += sizeof(uint32_t);

  return(i);
}
int
player_deser_player_dio_data(player_dio_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->count), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->digin), ((char*)src)+i, sizeof(uint32_t));
  dest->digin = ntohl(dest->digin);
  i += sizeof(uint32_t);

  return(i);
}

int
player_ser_player_aio_data(void* dest, player_aio_data_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.count), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_aio_data(player_aio_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->count), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_bps_data(void* dest, player_bps_data_t src)
{
  int i = 0;


  player_bps_data_t swappedsrc;

  swappedsrc.px = htonl(src.px);
  memcpy(((char*)dest)+i, &(swappedsrc.px), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.py = htonl(src.py);
  memcpy(((char*)dest)+i, &(swappedsrc.py), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.pa = htonl(src.pa);
  memcpy(((char*)dest)+i, &(swappedsrc.pa), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.ux = htonl(src.ux);
  memcpy(((char*)dest)+i, &(swappedsrc.ux), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.uy = htonl(src.uy);
  memcpy(((char*)dest)+i, &(swappedsrc.uy), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.ua = htonl(src.ua);
  memcpy(((char*)dest)+i, &(swappedsrc.ua), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.err = htonl(src.err);
  memcpy(((char*)dest)+i, &(swappedsrc.err), sizeof(uint32_t));
  i += sizeof(uint32_t);

  return(i);
}
int
player_deser_player_bps_data(player_bps_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->px), ((char*)src)+i, sizeof(uint32_t));
  dest->px = ntohl(dest->px);
  i += sizeof(uint32_t);
  memcpy(&(dest->py), ((char*)src)+i, sizeof(uint32_t));
  dest->py = ntohl(dest->py);
  i += sizeof(uint32_t);
  memcpy(&(dest->pa), ((char*)src)+i, sizeof(uint32_t));
  dest->pa = ntohl(dest->pa);
  i += sizeof(uint32_t);
  memcpy(&(dest->ux), ((char*)src)+i, sizeof(uint32_t));
  dest->ux = ntohl(dest->ux);
  i += sizeof(uint32_t);
  memcpy(&(dest->uy), ((char*)src)+i, sizeof(uint32_t));
  dest->uy = ntohl(dest->uy);
  i += sizeof(uint32_t);
  memcpy(&(dest->ua), ((char*)src)+i, sizeof(uint32_t));
  dest->ua = ntohl(dest->ua);
  i += sizeof(uint32_t);
  memcpy(&(dest->err), ((char*)src)+i, sizeof(uint32_t));
  dest->err = ntohl(dest->err);
  i += sizeof(uint32_t);

  return(i);
}

int
player_ser_player_bps_config(void* dest, player_bps_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_bps_config(player_bps_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_bps_beacon(void* dest, player_bps_beacon_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.subtype), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.id), sizeof(uint8_t));
  i += sizeof(uint8_t);

  player_bps_beacon_t swappedsrc;

  swappedsrc.px = htonl(src.px);
  memcpy(((char*)dest)+i, &(swappedsrc.px), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.py = htonl(src.py);
  memcpy(((char*)dest)+i, &(swappedsrc.py), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.pa = htonl(src.pa);
  memcpy(((char*)dest)+i, &(swappedsrc.pa), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.ux = htonl(src.ux);
  memcpy(((char*)dest)+i, &(swappedsrc.ux), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.uy = htonl(src.uy);
  memcpy(((char*)dest)+i, &(swappedsrc.uy), sizeof(uint32_t));
  i += sizeof(uint32_t);
  swappedsrc.ua = htonl(src.ua);
  memcpy(((char*)dest)+i, &(swappedsrc.ua), sizeof(uint32_t));
  i += sizeof(uint32_t);

  return(i);
}
int
player_deser_player_bps_beacon(player_bps_beacon_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->subtype), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->id), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->px), ((char*)src)+i, sizeof(uint32_t));
  dest->px = ntohl(dest->px);
  i += sizeof(uint32_t);
  memcpy(&(dest->py), ((char*)src)+i, sizeof(uint32_t));
  dest->py = ntohl(dest->py);
  i += sizeof(uint32_t);
  memcpy(&(dest->pa), ((char*)src)+i, sizeof(uint32_t));
  dest->pa = ntohl(dest->pa);
  i += sizeof(uint32_t);
  memcpy(&(dest->ux), ((char*)src)+i, sizeof(uint32_t));
  dest->ux = ntohl(dest->ux);
  i += sizeof(uint32_t);
  memcpy(&(dest->uy), ((char*)src)+i, sizeof(uint32_t));
  dest->uy = ntohl(dest->uy);
  i += sizeof(uint32_t);
  memcpy(&(dest->ua), ((char*)src)+i, sizeof(uint32_t));
  dest->ua = ntohl(dest->ua);
  i += sizeof(uint32_t);

  return(i);
}

int
player_ser_player_joystick_data(void* dest, player_joystick_data_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.xpos), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.ypos), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.button0), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.button1), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_joystick_data(player_joystick_data_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->xpos), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->ypos), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->button0), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->button1), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

int
player_ser_player_rwi_config(void* dest, player_rwi_config_t src)
{
  int i = 0;

  memcpy(((char*)dest)+i, &(src.request), sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(((char*)dest)+i, &(src.value), sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}
int
player_deser_player_rwi_config(player_rwi_config_t* dest, void* src)
{
  int i = 0;

  memcpy(&(dest->request), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);
  memcpy(&(dest->value), ((char*)src)+i, sizeof(uint8_t));
  i += sizeof(uint8_t);

  return(i);
}

