/*
  * $Id$
  *
  * This file automatically generated by gerkey at: 
  *   Wed May 11 04:16:44 PM PDT 2005
  */


#ifndef SERIALIZE_H
#define SERIALIZE_H

#ifdef __cplusplus
extern "C" {
#endif

int player_ser_player_msghdr(void* dest, player_msghdr_t src);

int player_deser_player_msghdr(player_msghdr_t* dest, void* src);

int player_ser_player_device_id(void* dest, player_device_id_t src);

int player_deser_player_device_id(player_device_id_t* dest, void* src);

int player_ser_player_device_devlist(void* dest, player_device_devlist_t src);

int player_deser_player_device_devlist(player_device_devlist_t* dest, void* src);

int player_ser_player_device_driverinfo(void* dest, player_device_driverinfo_t src);

int player_deser_player_device_driverinfo(player_device_driverinfo_t* dest, void* src);

int player_ser_player_device_req(void* dest, player_device_req_t src);

int player_deser_player_device_req(player_device_req_t* dest, void* src);

int player_ser_player_device_resp(void* dest, player_device_resp_t src);

int player_deser_player_device_resp(player_device_resp_t* dest, void* src);

int player_ser_player_device_data_req(void* dest, player_device_data_req_t src);

int player_deser_player_device_data_req(player_device_data_req_t* dest, void* src);

int player_ser_player_device_datamode_req(void* dest, player_device_datamode_req_t src);

int player_deser_player_device_datamode_req(player_device_datamode_req_t* dest, void* src);

int player_ser_player_device_datafreq_req(void* dest, player_device_datafreq_req_t src);

int player_deser_player_device_datafreq_req(player_device_datafreq_req_t* dest, void* src);

int player_ser_player_device_auth_req(void* dest, player_device_auth_req_t src);

int player_deser_player_device_auth_req(player_device_auth_req_t* dest, void* src);

int player_ser_player_device_nameservice_req(void* dest, player_device_nameservice_req_t src);

int player_deser_player_device_nameservice_req(player_device_nameservice_req_t* dest, void* src);

int player_ser_player_power_data(void* dest, player_power_data_t src);

int player_deser_player_power_data(player_power_data_t* dest, void* src);

int player_ser_player_gripper_data(void* dest, player_gripper_data_t src);

int player_deser_player_gripper_data(player_gripper_data_t* dest, void* src);

int player_ser_player_gripper_cmd(void* dest, player_gripper_cmd_t src);

int player_deser_player_gripper_cmd(player_gripper_cmd_t* dest, void* src);

int player_ser_player_motor_data(void* dest, player_motor_data_t src);

int player_deser_player_motor_data(player_motor_data_t* dest, void* src);

int player_ser_player_motor_cmd(void* dest, player_motor_cmd_t src);

int player_deser_player_motor_cmd(player_motor_cmd_t* dest, void* src);

int player_ser_player_motor_position_mode_req(void* dest, player_motor_position_mode_req_t src);

int player_deser_player_motor_position_mode_req(player_motor_position_mode_req_t* dest, void* src);

int player_ser_player_motor_velocitymode_config(void* dest, player_motor_velocitymode_config_t src);

int player_deser_player_motor_velocitymode_config(player_motor_velocitymode_config_t* dest, void* src);

int player_ser_player_motor_resetodom_config(void* dest, player_motor_resetodom_config_t src);

int player_deser_player_motor_resetodom_config(player_motor_resetodom_config_t* dest, void* src);

int player_ser_player_motor_set_odom_req(void* dest, player_motor_set_odom_req_t src);

int player_deser_player_motor_set_odom_req(player_motor_set_odom_req_t* dest, void* src);

int player_ser_player_motor_speed_pid_req(void* dest, player_motor_speed_pid_req_t src);

int player_deser_player_motor_speed_pid_req(player_motor_speed_pid_req_t* dest, void* src);

int player_ser_player_motor_position_pid_req(void* dest, player_motor_position_pid_req_t src);

int player_deser_player_motor_position_pid_req(player_motor_position_pid_req_t* dest, void* src);

int player_ser_player_motor_speed_prof_req(void* dest, player_motor_speed_prof_req_t src);

int player_deser_player_motor_speed_prof_req(player_motor_speed_prof_req_t* dest, void* src);

int player_ser_player_motor_power_config(void* dest, player_motor_power_config_t src);

int player_deser_player_motor_power_config(player_motor_power_config_t* dest, void* src);

int player_ser_player_position_data(void* dest, player_position_data_t src);

int player_deser_player_position_data(player_position_data_t* dest, void* src);

int player_ser_player_position_cmd(void* dest, player_position_cmd_t src);

int player_deser_player_position_cmd(player_position_cmd_t* dest, void* src);

int player_ser_player_position_geom(void* dest, player_position_geom_t src);

int player_deser_player_position_geom(player_position_geom_t* dest, void* src);

int player_ser_player_position_power_config(void* dest, player_position_power_config_t src);

int player_deser_player_position_power_config(player_position_power_config_t* dest, void* src);

int player_ser_player_position_velocitymode_config(void* dest, player_position_velocitymode_config_t src);

int player_deser_player_position_velocitymode_config(player_position_velocitymode_config_t* dest, void* src);

int player_ser_player_position_resetodom_config(void* dest, player_position_resetodom_config_t src);

int player_deser_player_position_resetodom_config(player_position_resetodom_config_t* dest, void* src);

int player_ser_player_position_position_mode_req(void* dest, player_position_position_mode_req_t src);

int player_deser_player_position_position_mode_req(player_position_position_mode_req_t* dest, void* src);

int player_ser_player_position_set_odom_req(void* dest, player_position_set_odom_req_t src);

int player_deser_player_position_set_odom_req(player_position_set_odom_req_t* dest, void* src);

int player_ser_player_position_speed_pid_req(void* dest, player_position_speed_pid_req_t src);

int player_deser_player_position_speed_pid_req(player_position_speed_pid_req_t* dest, void* src);

int player_ser_player_position_position_pid_req(void* dest, player_position_position_pid_req_t src);

int player_deser_player_position_position_pid_req(player_position_position_pid_req_t* dest, void* src);

int player_ser_player_position_speed_prof_req(void* dest, player_position_speed_prof_req_t src);

int player_deser_player_position_speed_prof_req(player_position_speed_prof_req_t* dest, void* src);

int player_ser_player_rmp_config(void* dest, player_rmp_config_t src);

int player_deser_player_rmp_config(player_rmp_config_t* dest, void* src);

int player_ser_player_position2d_data(void* dest, player_position2d_data_t src);

int player_deser_player_position2d_data(player_position2d_data_t* dest, void* src);

int player_ser_player_position2d_cmd(void* dest, player_position2d_cmd_t src);

int player_deser_player_position2d_cmd(player_position2d_cmd_t* dest, void* src);

int player_ser_player_position2d_geom(void* dest, player_position2d_geom_t src);

int player_deser_player_position2d_geom(player_position2d_geom_t* dest, void* src);

int player_ser_player_position2d_power_config(void* dest, player_position2d_power_config_t src);

int player_deser_player_position2d_power_config(player_position2d_power_config_t* dest, void* src);

int player_ser_player_position2d_velocitymode_config(void* dest, player_position2d_velocitymode_config_t src);

int player_deser_player_position2d_velocitymode_config(player_position2d_velocitymode_config_t* dest, void* src);

int player_ser_player_position2d_resetodom_config(void* dest, player_position2d_resetodom_config_t src);

int player_deser_player_position2d_resetodom_config(player_position2d_resetodom_config_t* dest, void* src);

int player_ser_player_position2d_position_mode_req(void* dest, player_position2d_position_mode_req_t src);

int player_deser_player_position2d_position_mode_req(player_position2d_position_mode_req_t* dest, void* src);

int player_ser_player_position2d_set_odom_req(void* dest, player_position2d_set_odom_req_t src);

int player_deser_player_position2d_set_odom_req(player_position2d_set_odom_req_t* dest, void* src);

int player_ser_player_position2d_speed_pid_req(void* dest, player_position2d_speed_pid_req_t src);

int player_deser_player_position2d_speed_pid_req(player_position2d_speed_pid_req_t* dest, void* src);

int player_ser_player_position2d_position_pid_req(void* dest, player_position2d_position_pid_req_t src);

int player_deser_player_position2d_position_pid_req(player_position2d_position_pid_req_t* dest, void* src);

int player_ser_player_position2d_speed_prof_req(void* dest, player_position2d_speed_prof_req_t src);

int player_deser_player_position2d_speed_prof_req(player_position2d_speed_prof_req_t* dest, void* src);

int player_ser_player_position3d_data(void* dest, player_position3d_data_t src);

int player_deser_player_position3d_data(player_position3d_data_t* dest, void* src);

int player_ser_player_position3d_cmd(void* dest, player_position3d_cmd_t src);

int player_deser_player_position3d_cmd(player_position3d_cmd_t* dest, void* src);

int player_ser_player_position3d_geom(void* dest, player_position3d_geom_t src);

int player_deser_player_position3d_geom(player_position3d_geom_t* dest, void* src);

int player_ser_player_position3d_power_config(void* dest, player_position3d_power_config_t src);

int player_deser_player_position3d_power_config(player_position3d_power_config_t* dest, void* src);

int player_ser_player_position3d_position_mode_req(void* dest, player_position3d_position_mode_req_t src);

int player_deser_player_position3d_position_mode_req(player_position3d_position_mode_req_t* dest, void* src);

int player_ser_player_position3d_velocitymode_config(void* dest, player_position3d_velocitymode_config_t src);

int player_deser_player_position3d_velocitymode_config(player_position3d_velocitymode_config_t* dest, void* src);

int player_ser_player_position3d_set_odom_req(void* dest, player_position3d_set_odom_req_t src);

int player_deser_player_position3d_set_odom_req(player_position3d_set_odom_req_t* dest, void* src);

int player_ser_player_position3d_resetodom_config(void* dest, player_position3d_resetodom_config_t src);

int player_deser_player_position3d_resetodom_config(player_position3d_resetodom_config_t* dest, void* src);

int player_ser_player_position3d_speed_pid_req(void* dest, player_position3d_speed_pid_req_t src);

int player_deser_player_position3d_speed_pid_req(player_position3d_speed_pid_req_t* dest, void* src);

int player_ser_player_position3d_position_pid_req(void* dest, player_position3d_position_pid_req_t src);

int player_deser_player_position3d_position_pid_req(player_position3d_position_pid_req_t* dest, void* src);

int player_ser_player_position3d_speed_prof_req(void* dest, player_position3d_speed_prof_req_t src);

int player_deser_player_position3d_speed_prof_req(player_position3d_speed_prof_req_t* dest, void* src);

int player_ser_player_sonar_data(void* dest, player_sonar_data_t src);

int player_deser_player_sonar_data(player_sonar_data_t* dest, void* src);

int player_ser_player_sonar_geom(void* dest, player_sonar_geom_t src);

int player_deser_player_sonar_geom(player_sonar_geom_t* dest, void* src);

int player_ser_player_sonar_power_config(void* dest, player_sonar_power_config_t src);

int player_deser_player_sonar_power_config(player_sonar_power_config_t* dest, void* src);

int player_ser_player_laser_data(void* dest, player_laser_data_t src);

int player_deser_player_laser_data(player_laser_data_t* dest, void* src);

int player_ser_player_laser_geom(void* dest, player_laser_geom_t src);

int player_deser_player_laser_geom(player_laser_geom_t* dest, void* src);

int player_ser_player_laser_config(void* dest, player_laser_config_t src);

int player_deser_player_laser_config(player_laser_config_t* dest, void* src);

int player_ser_player_laser_power_config(void* dest, player_laser_power_config_t src);

int player_deser_player_laser_power_config(player_laser_power_config_t* dest, void* src);

int player_ser_player_blobfinder_blob(void* dest, player_blobfinder_blob_t src);

int player_deser_player_blobfinder_blob(player_blobfinder_blob_t* dest, void* src);

int player_ser_player_blobfinder_data(void* dest, player_blobfinder_data_t src);

int player_deser_player_blobfinder_data(player_blobfinder_data_t* dest, void* src);

int player_ser_player_blobfinder_color_config(void* dest, player_blobfinder_color_config_t src);

int player_deser_player_blobfinder_color_config(player_blobfinder_color_config_t* dest, void* src);

int player_ser_player_blobfinder_imager_config(void* dest, player_blobfinder_imager_config_t src);

int player_deser_player_blobfinder_imager_config(player_blobfinder_imager_config_t* dest, void* src);

int player_ser_player_ptz_data(void* dest, player_ptz_data_t src);

int player_deser_player_ptz_data(player_ptz_data_t* dest, void* src);

int player_ser_player_ptz_cmd(void* dest, player_ptz_cmd_t src);

int player_deser_player_ptz_cmd(player_ptz_cmd_t* dest, void* src);

int player_ser_player_ptz_generic_config(void* dest, player_ptz_generic_config_t src);

int player_deser_player_ptz_generic_config(player_ptz_generic_config_t* dest, void* src);

int player_ser_player_ptz_velocitymode_config(void* dest, player_ptz_velocitymode_config_t src);

int player_deser_player_ptz_velocitymode_config(player_ptz_velocitymode_config_t* dest, void* src);

int player_ser_player_camera_data(void* dest, player_camera_data_t src);

int player_deser_player_camera_data(player_camera_data_t* dest, void* src);

int player_ser_player_audio_data(void* dest, player_audio_data_t src);

int player_deser_player_audio_data(player_audio_data_t* dest, void* src);

int player_ser_player_audio_cmd(void* dest, player_audio_cmd_t src);

int player_deser_player_audio_cmd(player_audio_cmd_t* dest, void* src);

int player_ser_player_audiodsp_data(void* dest, player_audiodsp_data_t src);

int player_deser_player_audiodsp_data(player_audiodsp_data_t* dest, void* src);

int player_ser_player_audiodsp_cmd(void* dest, player_audiodsp_cmd_t src);

int player_deser_player_audiodsp_cmd(player_audiodsp_cmd_t* dest, void* src);

int player_ser_player_audiodsp_config(void* dest, player_audiodsp_config_t src);

int player_deser_player_audiodsp_config(player_audiodsp_config_t* dest, void* src);

int player_ser_player_audiomixer_cmd(void* dest, player_audiomixer_cmd_t src);

int player_deser_player_audiomixer_cmd(player_audiomixer_cmd_t* dest, void* src);

int player_ser_player_audiomixer_config(void* dest, player_audiomixer_config_t src);

int player_deser_player_audiomixer_config(player_audiomixer_config_t* dest, void* src);

int player_ser_player_waveform_data(void* dest, player_waveform_data_t src);

int player_deser_player_waveform_data(player_waveform_data_t* dest, void* src);

int player_ser_player_blinkenlight_data(void* dest, player_blinkenlight_data_t src);

int player_deser_player_blinkenlight_data(player_blinkenlight_data_t* dest, void* src);

int player_ser_player_fiducial_item(void* dest, player_fiducial_item_t src);

int player_deser_player_fiducial_item(player_fiducial_item_t* dest, void* src);

int player_ser_player_fiducial_data(void* dest, player_fiducial_data_t src);

int player_deser_player_fiducial_data(player_fiducial_data_t* dest, void* src);

int player_ser_player_fiducial_geom(void* dest, player_fiducial_geom_t src);

int player_deser_player_fiducial_geom(player_fiducial_geom_t* dest, void* src);

int player_ser_player_fiducial_fov(void* dest, player_fiducial_fov_t src);

int player_deser_player_fiducial_fov(player_fiducial_fov_t* dest, void* src);

int player_ser_player_fiducial_id(void* dest, player_fiducial_id_t src);

int player_deser_player_fiducial_id(player_fiducial_id_t* dest, void* src);

int player_ser_player_fiducial_msg(void* dest, player_fiducial_msg_t src);

int player_deser_player_fiducial_msg(player_fiducial_msg_t* dest, void* src);

int player_ser_player_fiducial_msg_rx_req(void* dest, player_fiducial_msg_rx_req_t src);

int player_deser_player_fiducial_msg_rx_req(player_fiducial_msg_rx_req_t* dest, void* src);

int player_ser_player_fiducial_msg_tx_req(void* dest, player_fiducial_msg_tx_req_t src);

int player_deser_player_fiducial_msg_tx_req(player_fiducial_msg_tx_req_t* dest, void* src);

int player_ser_player_fiducial_msg_txrx_req(void* dest, player_fiducial_msg_txrx_req_t src);

int player_deser_player_fiducial_msg_txrx_req(player_fiducial_msg_txrx_req_t* dest, void* src);

int player_ser_player_speech_cmd(void* dest, player_speech_cmd_t src);

int player_deser_player_speech_cmd(player_speech_cmd_t* dest, void* src);

int player_ser_player_gps_data(void* dest, player_gps_data_t src);

int player_deser_player_gps_data(player_gps_data_t* dest, void* src);

int player_ser_player_bumper_data(void* dest, player_bumper_data_t src);

int player_deser_player_bumper_data(player_bumper_data_t* dest, void* src);

int player_ser_player_bumper_define(void* dest, player_bumper_define_t src);

int player_deser_player_bumper_define(player_bumper_define_t* dest, void* src);

int player_ser_player_bumper_geom(void* dest, player_bumper_geom_t src);

int player_deser_player_bumper_geom(player_bumper_geom_t* dest, void* src);

int player_ser_player_truth_data(void* dest, player_truth_data_t src);

int player_deser_player_truth_data(player_truth_data_t* dest, void* src);

int player_ser_player_truth_pose(void* dest, player_truth_pose_t src);

int player_deser_player_truth_pose(player_truth_pose_t* dest, void* src);

int player_ser_player_truth_fiducial_id(void* dest, player_truth_fiducial_id_t src);

int player_deser_player_truth_fiducial_id(player_truth_fiducial_id_t* dest, void* src);

int player_ser_player_simulation_data(void* dest, player_simulation_data_t src);

int player_deser_player_simulation_data(player_simulation_data_t* dest, void* src);

int player_ser_player_simulation_cmd(void* dest, player_simulation_cmd_t src);

int player_deser_player_simulation_cmd(player_simulation_cmd_t* dest, void* src);

int player_ser_player_simulation_pose2d_req(void* dest, player_simulation_pose2d_req_t src);

int player_deser_player_simulation_pose2d_req(player_simulation_pose2d_req_t* dest, void* src);

int player_ser_player_dio_data(void* dest, player_dio_data_t src);

int player_deser_player_dio_data(player_dio_data_t* dest, void* src);

int player_ser_player_dio_cmd(void* dest, player_dio_cmd_t src);

int player_deser_player_dio_cmd(player_dio_cmd_t* dest, void* src);

int player_ser_player_aio_data(void* dest, player_aio_data_t src);

int player_deser_player_aio_data(player_aio_data_t* dest, void* src);

int player_ser_player_joystick_data(void* dest, player_joystick_data_t src);

int player_deser_player_joystick_data(player_joystick_data_t* dest, void* src);

int player_ser_player_wifi_link(void* dest, player_wifi_link_t src);

int player_deser_player_wifi_link(player_wifi_link_t* dest, void* src);

int player_ser_player_wifi_data(void* dest, player_wifi_data_t src);

int player_deser_player_wifi_data(player_wifi_data_t* dest, void* src);

int player_ser_player_wifi_mac_req(void* dest, player_wifi_mac_req_t src);

int player_deser_player_wifi_mac_req(player_wifi_mac_req_t* dest, void* src);

int player_ser_player_wifi_iwspy_addr_req(void* dest, player_wifi_iwspy_addr_req_t src);

int player_deser_player_wifi_iwspy_addr_req(player_wifi_iwspy_addr_req_t* dest, void* src);

int player_ser_player_ir_data(void* dest, player_ir_data_t src);

int player_deser_player_ir_data(player_ir_data_t* dest, void* src);

int player_ser_player_ir_pose(void* dest, player_ir_pose_t src);

int player_deser_player_ir_pose(player_ir_pose_t* dest, void* src);

int player_ser_player_ir_pose_req(void* dest, player_ir_pose_req_t src);

int player_deser_player_ir_pose_req(player_ir_pose_req_t* dest, void* src);

int player_ser_player_ir_power_req(void* dest, player_ir_power_req_t src);

int player_deser_player_ir_power_req(player_ir_power_req_t* dest, void* src);

int player_ser_player_localize_hypoth(void* dest, player_localize_hypoth_t src);

int player_deser_player_localize_hypoth(player_localize_hypoth_t* dest, void* src);

int player_ser_player_localize_data(void* dest, player_localize_data_t src);

int player_deser_player_localize_data(player_localize_data_t* dest, void* src);

int player_ser_player_localize_set_pose(void* dest, player_localize_set_pose_t src);

int player_deser_player_localize_set_pose(player_localize_set_pose_t* dest, void* src);

int player_ser_player_localize_config(void* dest, player_localize_config_t src);

int player_deser_player_localize_config(player_localize_config_t* dest, void* src);

int player_ser_player_localize_particle(void* dest, player_localize_particle_t src);

int player_deser_player_localize_particle(player_localize_particle_t* dest, void* src);

int player_ser_player_localize_get_particles(void* dest, player_localize_get_particles_t src);

int player_deser_player_localize_get_particles(player_localize_get_particles_t* dest, void* src);

int player_ser_player_map_info(void* dest, player_map_info_t src);

int player_deser_player_map_info(player_map_info_t* dest, void* src);

int player_ser_player_map_data(void* dest, player_map_data_t src);

int player_deser_player_map_data(player_map_data_t* dest, void* src);

int player_ser_player_mcom_data(void* dest, player_mcom_data_t src);

int player_deser_player_mcom_data(player_mcom_data_t* dest, void* src);

int player_ser_player_mcom_config(void* dest, player_mcom_config_t src);

int player_deser_player_mcom_config(player_mcom_config_t* dest, void* src);

int player_ser_player_mcom_return(void* dest, player_mcom_return_t src);

int player_deser_player_mcom_return(player_mcom_return_t* dest, void* src);

int player_ser_player_nomad_data(void* dest, player_nomad_data_t src);

int player_deser_player_nomad_data(player_nomad_data_t* dest, void* src);

int player_ser_player_nomad_cmd(void* dest, player_nomad_cmd_t src);

int player_deser_player_nomad_cmd(player_nomad_cmd_t* dest, void* src);

int player_ser_player_sound_cmd(void* dest, player_sound_cmd_t src);

int player_deser_player_sound_cmd(player_sound_cmd_t* dest, void* src);

int player_ser_player_energy_data(void* dest, player_energy_data_t src);

int player_deser_player_energy_data(player_energy_data_t* dest, void* src);

int player_ser_player_energy_chargepolicy_config(void* dest, player_energy_chargepolicy_config_t src);

int player_deser_player_energy_chargepolicy_config(player_energy_chargepolicy_config_t* dest, void* src);

int player_ser_player_planner_data(void* dest, player_planner_data_t src);

int player_deser_player_planner_data(player_planner_data_t* dest, void* src);

int player_ser_player_planner_cmd(void* dest, player_planner_cmd_t src);

int player_deser_player_planner_cmd(player_planner_cmd_t* dest, void* src);

int player_ser_player_planner_waypoint(void* dest, player_planner_waypoint_t src);

int player_deser_player_planner_waypoint(player_planner_waypoint_t* dest, void* src);

int player_ser_player_planner_waypoints_req(void* dest, player_planner_waypoints_req_t src);

int player_deser_player_planner_waypoints_req(player_planner_waypoints_req_t* dest, void* src);

int player_ser_player_planner_enable_req(void* dest, player_planner_enable_req_t src);

int player_deser_player_planner_enable_req(player_planner_enable_req_t* dest, void* src);

int player_ser_player_log_set_write_state(void* dest, player_log_set_write_state_t src);

int player_deser_player_log_set_write_state(player_log_set_write_state_t* dest, void* src);

int player_ser_player_log_set_read_state(void* dest, player_log_set_read_state_t src);

int player_deser_player_log_set_read_state(player_log_set_read_state_t* dest, void* src);

int player_ser_player_log_set_read_rewind(void* dest, player_log_set_read_rewind_t src);

int player_deser_player_log_set_read_rewind(player_log_set_read_rewind_t* dest, void* src);

int player_ser_player_log_get_state(void* dest, player_log_get_state_t src);

int player_deser_player_log_get_state(player_log_get_state_t* dest, void* src);

int player_ser_player_log_set_filename(void* dest, player_log_set_filename_t src);

int player_deser_player_log_set_filename(player_log_set_filename_t* dest, void* src);

int player_ser_player_speech_recognition_data(void* dest, player_speech_recognition_data_t src);

int player_deser_player_speech_recognition_data(player_speech_recognition_data_t* dest, void* src);

#ifdef __cplusplus
}
#endif

#endif
