###########################################################################
# Desc: Makefile for Player Viewer
# Author: Brian Gerkey
# Date: May 29 2002
# CVS: $Id$
###########################################################################

include ../../Makefile.common

###########################################################################
# Build section
###########################################################################

all:

dep:

clean_dep:

clean: 




###########################################################################
# Install
###########################################################################
install:
	$(MKDIR) -p $(INSTALL_UTILS)
	$(INSTALL) -m 755 viewer.tk $(INSTALL_UTILS)
	$(INSTALL) -m 644 README $(INSTALL_UTILS)/README.tkplayerv

uninstall:
	$(RM) -f $(INSTALL_UTILS)/viewer.tk
	$(RM) -f $(INSTALL_UTILS)/README.tkplayerv

