#
# $Id$
#

include ../Makefile.common

all:
	cd playerv && make all
	cd tkplayerv && make all

install:
	cd playerv && make install
	cd tkplayerv && make install

uninstall:
	cd playerv && make uninstall
	cd tkplayerv && make uninstall

dep:
	cd playerv && make dep
	cd tkplayerv && make dep
	
clean:
	cd playerv && make clean
	cd tkplayerv && make clean

clean_dep:
	cd playerv && make clean_dep
	cd tkplayerv && make clean_dep

