#
# $Id$
#

include ../Makefile.common

all:
	cd playerv && make all
	cd tkviewer && make all

install:
	cd playerv && make install
	cd tkviewer && make install

uninstall:
	cd playerv && make uninstall
	cd tkviewer && make uninstall

dep:
	cd playerv && make dep
	cd tkviewer && make dep
	
clean:
	cd playerv && make clean
	cd tkviewer && make clean

clean_dep:
	cd playerv && make clean_dep
	cd tkviewer && make clean_dep

