#
# $Id$
#

include ../Makefile.common

all:
	cd playerv && make all

install:
	cd playerv && make install

uninstall:
	cd playerv && make uninstall

dep:
	cd playerv && make dep
	
clean:
	cd playerv && make clean

clean_dep:
	cd playerv && make clean_dep

