CFLAGS = -I. -I../../../.. -Wall -Werror -O2 -g `pkg-config --cflags gdk-pixbuf-2.0`
LIBS = -L../../../../libplayercore/.libs -lplayererror `pkg-config --libs gdk-pixbuf-2.0`

SRCS = test.c plan.c plan_plan.c plan_waypoint.c

test: $(SRCS) plan.h
	gcc $(CFLAGS) -o $@ $(SRCS) $(LIBS)

clean:
	rm -f test
