/*
 *  Player - One Hell of a Robot Server
 *  Copyright (C) 2000
 *     Brian Gerkey, Kasper Stoy, Richard Vaughan, & Andrew Howard
 *                   
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

/* 
 * robot_params.cc 
 *
 * ActivMedia robot parameters, automatically generated by saphconv.tcl from 
 * Saphira parameter files:
 *    amigo.p
 *    p2at.p
 *    p2ce.p
 *    p2de.p
 *    p2dx.p
 *    p2it.p
 *    p2pb.p
 *    p2pp.p
 *    pion1m.p
 *    pion1x.p
 *    pionat.p
 *    psos1m.p
 *    psos1x.p
*/
#include <robot_params.h>


RobotParams_General_t amigo_General = 
{
  "Pioneer",
  "amigo",
  180.000000,
  120.000000,
  1,
  300.000000,
  1000.000000,
  1,
};

RobotParams_ConvFactors_t amigo_ConvFactors = 
{
  0.001534,
  0.508300,
  0.615400,
  1.000000,
  0.011000,
  20.000000,
};

RobotParams_Accessories_t amigo_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t amigo_Sonar = 
{
  8,
};

RobotParams_General_t p2at_General = 
{
  "Pioneer",
  "p2at",
  500.000000,
  120.000000,
  1,
  300.000000,
  1200.000000,
  1,
};

RobotParams_ConvFactors_t p2at_ConvFactors = 
{
  0.001534,
  1.320000,
  1.000000,
  0.268000,
  0.003400,
  20.000000,
};

RobotParams_Accessories_t p2at_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t p2at_Sonar = 
{
  16,
};

RobotParams_General_t p2ce_General = 
{
  "Pioneer",
  "p2ce",
  250.000000,
  120.000000,
  1,
  500.000000,
  2200.000000,
  1,
};

RobotParams_ConvFactors_t p2ce_ConvFactors = 
{
  0.001534,
  0.826000,
  1.000000,
  0.268000,
  0.005700,
  20.000000,
};

RobotParams_Accessories_t p2ce_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t p2ce_Sonar = 
{
  16,
};

RobotParams_General_t p2de_General = 
{
  "Pioneer",
  "p2de",
  250.000000,
  120.000000,
  1,
  500.000000,
  2200.000000,
  1,
};

RobotParams_ConvFactors_t p2de_ConvFactors = 
{
  0.001534,
  0.969000,
  1.000000,
  0.268000,
  0.005600,
  20.000000,
};

RobotParams_Accessories_t p2de_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t p2de_Sonar = 
{
  16,
};

RobotParams_General_t p2dx_General = 
{
  "Pioneer",
  "p2dx",
  250.000000,
  120.000000,
  1,
  500.000000,
  2200.000000,
  1,
};

RobotParams_ConvFactors_t p2dx_ConvFactors = 
{
  0.001534,
  0.840000,
  1.000000,
  0.268000,
  0.005600,
  20.000000,
};

RobotParams_Accessories_t p2dx_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t p2dx_Sonar = 
{
  16,
};

RobotParams_General_t p2it_General = 
{
  "Pioneer",
  "p2it",
  500.000000,
  120.000000,
  1,
  300.000000,
  1200.000000,
  1,
};

RobotParams_ConvFactors_t p2it_ConvFactors = 
{
  0.001534,
  1.136000,
  1.000000,
  0.268000,
  0.003200,
  20.000000,
};

RobotParams_Accessories_t p2it_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t p2it_Sonar = 
{
  16,
};

RobotParams_General_t p2pb_General = 
{
  "Pioneer",
  "p2pb",
  300.000000,
  120.000000,
  1,
  500.000000,
  2200.000000,
  1,
};

RobotParams_ConvFactors_t p2pb_ConvFactors = 
{
  0.001534,
  0.424000,
  1.000000,
  0.268000,
  0.005600,
  20.000000,
};

RobotParams_Accessories_t p2pb_Accessories = 
{
  0,
  1,
  1,
};

RobotParams_Sonar_t p2pb_Sonar = 
{
  16,
};

RobotParams_General_t p2pp_General = 
{
  "Pioneer",
  "p2pp",
  300.000000,
  120.000000,
  1,
  500.000000,
  2200.000000,
  1,
};

RobotParams_ConvFactors_t p2pp_ConvFactors = 
{
  0.001534,
  0.969000,
  1.000000,
  0.268000,
  0.006000,
  20.000000,
};

RobotParams_Accessories_t p2pp_Accessories = 
{
  1,
  1,
  1,
};

RobotParams_Sonar_t p2pp_Sonar = 
{
  16,
};

RobotParams_General_t pion1m_General = 
{
  "Pioneer",
  "pion1m",
  220.000000,
  90.000000,
  1,
  100.000000,
  400.000000,
  0,
};

RobotParams_ConvFactors_t pion1m_ConvFactors = 
{
  0.006136,
  0.050660,
  2.533200,
  0.173400,
  0.003300,
  4.000000,
};

RobotParams_Accessories_t pion1m_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t pion1m_Sonar = 
{
  7,
};

RobotParams_General_t pion1x_General = 
{
  "Pioneer",
  "pion1x",
  220.000000,
  90.000000,
  1,
  100.000000,
  400.000000,
  0,
};

RobotParams_ConvFactors_t pion1x_ConvFactors = 
{
  0.006136,
  0.050660,
  0.079790,
  0.173400,
  0.003333,
  4.000000,
};

RobotParams_Accessories_t pion1x_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t pion1x_Sonar = 
{
  7,
};

RobotParams_General_t pionat_General = 
{
  "Pioneer",
  "pionat",
  330.000000,
  120.000000,
  1,
  100.000000,
  500.000000,
  0,
};

RobotParams_ConvFactors_t pionat_ConvFactors = 
{
  0.006136,
  0.070000,
  2.533200,
  0.173400,
  0.003333,
  4.000000,
};

RobotParams_Accessories_t pionat_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t pionat_Sonar = 
{
  7,
};

RobotParams_General_t psos1m_General = 
{
  "Pioneer",
  "psos1m",
  220.000000,
  90.000000,
  1,
  100.000000,
  400.000000,
  0,
};

RobotParams_ConvFactors_t psos1m_ConvFactors = 
{
  0.006136,
  0.050660,
  2.533200,
  0.173400,
  0.003300,
  4.000000,
};

RobotParams_Accessories_t psos1m_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t psos1m_Sonar = 
{
  7,
};

RobotParams_General_t psos1x_General = 
{
  "Pioneer",
  "psos1x",
  220.000000,
  90.000000,
  1,
  100.000000,
  400.000000,
  0,
};

RobotParams_ConvFactors_t psos1x_ConvFactors = 
{
  0.006136,
  0.050660,
  0.079790,
  0.173400,
  0.003333,
  4.000000,
};

RobotParams_Accessories_t psos1x_Accessories = 
{
  0,
  0,
  0,
};

RobotParams_Sonar_t psos1x_Sonar = 
{
  7,
};

RobotParams_t PlayerRobotParams[PLAYER_NUM_ROBOT_TYPES];

void
initialize_robot_params(void)
{
  PlayerRobotParams[0].General =  amigo_General;
  PlayerRobotParams[0].ConvFactors =  amigo_ConvFactors;
  PlayerRobotParams[0].Accessories =  amigo_Accessories;
  PlayerRobotParams[0].Sonar =  amigo_Sonar;
  PlayerRobotParams[1].General =  p2at_General;
  PlayerRobotParams[1].ConvFactors =  p2at_ConvFactors;
  PlayerRobotParams[1].Accessories =  p2at_Accessories;
  PlayerRobotParams[1].Sonar =  p2at_Sonar;
  PlayerRobotParams[2].General =  p2ce_General;
  PlayerRobotParams[2].ConvFactors =  p2ce_ConvFactors;
  PlayerRobotParams[2].Accessories =  p2ce_Accessories;
  PlayerRobotParams[2].Sonar =  p2ce_Sonar;
  PlayerRobotParams[3].General =  p2de_General;
  PlayerRobotParams[3].ConvFactors =  p2de_ConvFactors;
  PlayerRobotParams[3].Accessories =  p2de_Accessories;
  PlayerRobotParams[3].Sonar =  p2de_Sonar;
  PlayerRobotParams[4].General =  p2dx_General;
  PlayerRobotParams[4].ConvFactors =  p2dx_ConvFactors;
  PlayerRobotParams[4].Accessories =  p2dx_Accessories;
  PlayerRobotParams[4].Sonar =  p2dx_Sonar;
  PlayerRobotParams[5].General =  p2it_General;
  PlayerRobotParams[5].ConvFactors =  p2it_ConvFactors;
  PlayerRobotParams[5].Accessories =  p2it_Accessories;
  PlayerRobotParams[5].Sonar =  p2it_Sonar;
  PlayerRobotParams[6].General =  p2pb_General;
  PlayerRobotParams[6].ConvFactors =  p2pb_ConvFactors;
  PlayerRobotParams[6].Accessories =  p2pb_Accessories;
  PlayerRobotParams[6].Sonar =  p2pb_Sonar;
  PlayerRobotParams[7].General =  p2pp_General;
  PlayerRobotParams[7].ConvFactors =  p2pp_ConvFactors;
  PlayerRobotParams[7].Accessories =  p2pp_Accessories;
  PlayerRobotParams[7].Sonar =  p2pp_Sonar;
  PlayerRobotParams[8].General =  pion1m_General;
  PlayerRobotParams[8].ConvFactors =  pion1m_ConvFactors;
  PlayerRobotParams[8].Accessories =  pion1m_Accessories;
  PlayerRobotParams[8].Sonar =  pion1m_Sonar;
  PlayerRobotParams[9].General =  pion1x_General;
  PlayerRobotParams[9].ConvFactors =  pion1x_ConvFactors;
  PlayerRobotParams[9].Accessories =  pion1x_Accessories;
  PlayerRobotParams[9].Sonar =  pion1x_Sonar;
  PlayerRobotParams[10].General =  pionat_General;
  PlayerRobotParams[10].ConvFactors =  pionat_ConvFactors;
  PlayerRobotParams[10].Accessories =  pionat_Accessories;
  PlayerRobotParams[10].Sonar =  pionat_Sonar;
  PlayerRobotParams[11].General =  psos1m_General;
  PlayerRobotParams[11].ConvFactors =  psos1m_ConvFactors;
  PlayerRobotParams[11].Accessories =  psos1m_Accessories;
  PlayerRobotParams[11].Sonar =  psos1m_Sonar;
  PlayerRobotParams[12].General =  psos1x_General;
  PlayerRobotParams[12].ConvFactors =  psos1x_ConvFactors;
  PlayerRobotParams[12].Accessories =  psos1x_Accessories;
  PlayerRobotParams[12].Sonar =  psos1x_Sonar;
}
