# This file was generated by CMake for @PROJECT_NAME@ library @PKG_NAME@
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=${prefix}/@PLAYER_LIBRARY_INSTALL_DIR@
includedir=${prefix}/include

Name: @PKG_NAME@
Description: @PKG_DESC@
Version: @PLAYER_VERSION@
Requires: @PKG_EXTERNAL_DEPS@
Libs: -L${libdir} -l@PKG_NAME@ @PKG_LIBFLAGS@ @PKG_INTERNAL_DEPS@
Cflags: -I${includedir}/player-@PLAYER_MAJOR_VERSION@.@PLAYER_MINOR_VERSION@ @PKG_CFLAGS@
