/*
 *  Player - One Hell of a Robot Server
 *  Copyright (C) 2000
 *     Brian Gerkey, Kasper Stoy, Richard Vaughan, & Andrew Howard
 *                   
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

/* 
 * robot_params.h 
 *
 * ActivMedia robot parameters, automatically generated by saphconv.tcl from 
 * Saphira parameter files:
 *    /usr/local/Saphira/params/amigo.p
 *    /usr/local/Saphira/params/p2at.p
 *    /usr/local/Saphira/params/p2ce.p
 *    /usr/local/Saphira/params/p2d8.p
 *    /usr/local/Saphira/params/p2de.p
 *    /usr/local/Saphira/params/p2df.p
 *    /usr/local/Saphira/params/p2dx.p
 *    /usr/local/Saphira/params/p2it.p
 *    /usr/local/Saphira/params/p2pb.p
 *    /usr/local/Saphira/params/p2pp.p
 *    /usr/local/Saphira/params/perfpb.p
 *    /usr/local/Saphira/params/pion1m.p
 *    /usr/local/Saphira/params/pion1x.p
 *    /usr/local/Saphira/params/pionat.p
 *    /usr/local/Saphira/params/prbt.p
 *    /usr/local/Saphira/params/psos1m.p
 *    /usr/local/Saphira/params/psos1x.p
*/

#ifndef _ROBOT_PARAMS_H
#define _ROBOT_PARAMS_H


void initialize_robot_params(void);

#define PLAYER_NUM_ROBOT_TYPES 17


typedef struct
{
  double x;
  double y;
  double th;
} sonar_pose_t;


typedef struct
{
  double AngleConvFactor; // 
  char* Class;
  double DiffConvFactor; // 
  double DistConvFactor; // 
  int FrontBumpers; // 
  int HasMoveCommand; // 
  double Holonomic; // 
  int LaserFlipped; // 
  char* LaserPort;
  int LaserPossessed; // 
  int LaserPowerControlled; // 
  int LaserX; // 
  int LaserY; // 
  double MaxRVelocity; // 
  double MaxVelocity; // 
  int NewTableSensingIR; // 
  int NumFrontBumpers; // 
  int NumRearBumpers; // 
  double RangeConvFactor; // 
  int RearBumpers; // 
  int RequestIOPackets; // 
  double RobotDiagonal; // 
  double RobotRadius; // 
  int SonarNum; // 
  char* Subclass;
  int TableSensingIR; // 
  double Vel2Divisor; // 
  double VelConvFactor; // 
  sonar_pose_t sonar_pose[31];
} RobotParams_t;


extern RobotParams_t PlayerRobotParams[];


#endif
