OPTION (PLAYER_CPPCHECK OFF "Enable a cppcheck target for Player")

IF (PLAYER_CPPCHECK)
  FIND_PROGRAM (CPPCHECK_EXECUTABLE cppcheck)
  IF (CPPCHECK_EXECUTABLE)
    EXECUTE_PROCESS (COMMAND ${CPPCHECK_EXECUTABLE} --version
      OUTPUT_VARIABLE CPPCHECK_VERSION)
    STRING (REPLACE "Cppcheck" "" CPPCHECK_VERSION ${CPPCHECK_VERSION})
    IF (${CPPCHECK_VERSION} VERSION_LESS "1.76")
      MESSAGE (WARNING "Cppcheck 1.76 or higher required for cppcheck target")
    ELSE (${CPPCHECK_VERSION} VERSION_LESS "1.76")
      SET (CMAKE_EXPORT_COMPILE_COMMANDS ON)
      ADD_CUSTOM_TARGET(cppcheck ${CPPCHECK_EXECUTABLE} --enable=all --project=${PROJECT_BINARY_DIR}/compile_commands.json
        WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
        COMMENT("Running cppcheck")
      )
    ENDIF (${CPPCHECK_VERSION} VERSION_LESS "1.76")
  ENDIF (CPPCHECK_EXECUTABLE)
ENDIF (PLAYER_CPPCHECK)
