# Find version components
STRING (REGEX REPLACE "^([0-9]+).*" "\\1" PLAYER_MAJOR_VERSION "${PLAYER_VERSION}")
STRING (REGEX REPLACE "^[0-9]+\\.([0-9]+).*" "\\1" PLAYER_MINOR_VERSION "${PLAYER_VERSION}")
STRING (REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+)" "\\1" PLAYER_REVISION_VERSION ${PLAYER_VERSION})
STRING (REGEX REPLACE "^[0-9]+\\.[0-9]+\\.[0-9]+(.*)" "\\1" PLAYER_CANDIDATE_VERSION ${PLAYER_VERSION})